name: Docs

on:
  push:
    branches: [master]
  pull_request:

concurrency:
  group: docs

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ruby
      - run: sudo apt-get update
      - run: sudo apt-get install -y --no-install-recommends doxygen
      - run: corepack enable yarn
      - run: yarn install
      - run: bundle install
      - run: bundle exec rake doc
      - uses: actions/upload-pages-artifact@v3
        with:
          path: tmp/doxygen/html/

  deploy:
    if: ${{ github.ref == 'refs/heads/master' }}
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    permissions:
      pages: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - id: deployment
        uses: actions/deploy-pages@v4
