name: Ruby

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '0 15 * * 5'

jobs:
  matrix:
    outputs:
      json: ${{ steps.read-matrix.outputs.json }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          repository: hanazuki/ruby-builder
      - id: read-matrix
        run: |
          echo "json=$(cat matrix.json)" >>"$GITHUB_OUTPUT"

  build:
    needs: matrix
    runs-on: ubuntu-24.04
    name: ruby-${{ matrix.ruby }} ${{ matrix.compilers.cxx }}
    strategy:
      fail-fast: false
      matrix:
        include: ${{fromJson(needs.matrix.outputs.json)}}
    steps:
      - uses: actions/checkout@v4
      - uses: oras-project/setup-oras@v1
      - name: Log in to ghcr.io
        run: |
          printenv GITHUB_TOKEN | oras login ghcr.io --username gh --password-stdin
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Set up Ruby
        run: |
          mkdir -p "$PREFIX"

          pushd /tmp
          oras pull "$TAG"
          tar xf ruby.tar.zst -C "$PREFIX"
          popd

          echo "$PREFIX/bin" >>"$GITHUB_PATH"
        env:
          TAG: ${{ matrix.artifact_tag }}
          PREFIX: ${{ matrix.install_prefix }}
      - name: Show environment
        run: |
          bundle env
      - name: Install gems
        run: |
          bundle install
      - name: Compile extensions
        run: |
          bundle exec rake compile
      - name: Run rspec
        run: |
          bundle exec rake spec
