name: Ruby

on:
  push:
    branches: [master]
  pull_request:
  schedule:
    - cron: '0 15 * * 5'

jobs:
  build:
    runs-on: ubuntu-24.04
    name: Ruby ${{ matrix.ruby }} ${{ matrix.cxx }}
    strategy:
      matrix:
        ruby:
          - '3.3'
          - '3.4.0-preview2'
        cxx:
          - clang++
          - g++

    steps:
      - uses: actions/checkout@v4
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Compiler version
        run: |
          "$CXX" --version
        env:
          CXX: ${{ matrix.cxx }}
      - name: Compile extensions
        run: |
          bundle exec rake compile
        env:
          CXX: ${{ matrix.cxx }}
      - name: Run rspec
        run: |
          bundle exec rake spec
